"""Pydantic schemas — split by domain (Wave 6)."""

from app.schemas.auth import *  # noqa: F403
from app.schemas.clients import *  # noqa: F403
from app.schemas.assets import *  # noqa: F403
from app.schemas.templates import *  # noqa: F403
from app.schemas.work_orders import *  # noqa: F403
from app.schemas.billing import *  # noqa: F403
from app.schemas.notifications import *  # noqa: F403
from app.schemas.platform import *  # noqa: F403
from app.schemas.labor import *  # noqa: F403
from app.schemas.locations import *  # noqa: F403
from app.schemas.dashboard import *  # noqa: F403
from app.schemas.common import *  # noqa: F403

__all__ = [
    "AiSchedulingStubOut",
    "ApproveReportBody",
    "AssetCreate",
    "AssetImportPreview",
    "AssetImportRow",
    "AssetOut",
    "AssetUpdate",
    "AssignBody",
    "AuditLogOut",
    "CategoryObservationsOut",
    "CategoryObservationsUpdate",
    "ClientCreate",
    "ClientOut",
    "ClientProvisionRequest",
    "ClientProvisionResponse",
    "ClientSummaryOut",
    "ClientUpdate",
    "CommentCreate",
    "CommentOut",
    "ContractCreate",
    "ContractOut",
    "DashboardSummaryOut",
    "DeclineRequestBody",
    "DocumentCreate",
    "DocumentOut",
    "GenerateInvoiceBody",
    "InvoiceLineOut",
    "InvoiceOut",
    "InvoicePatchBody",
    "InvoicePreviewOut",
    "LaborEntryCreate",
    "LaborEntryOut",
    "LocationCreate",
    "LocationOut",
    "LocationTreeNode",
    "LocationUpdate",
    "LoginRequest",
    "MaintenanceCalendarEventOut",
    "MaintenanceCompanyOut",
    "MaintenanceReportOut",
    "MaintenanceScheduleCreate",
    "MaintenanceScheduleOut",
    "NotificationOut",
    "ObservationFieldDef",
    "PaginatedMeta",
    "PaginatedWorkOrders",
    "PartCreate",
    "PartOut",
    "PlatformClientBrief",
    "PlatformClientCreate",
    "PlatformUserCreate",
    "PlatformUserCreateOut",
    "PricingProfileCreate",
    "PricingProfileOut",
    "RefreshRequest",
    "RejectReportBody",
    "ReportAnswersUpdate",
    "ReportTemplateCreate",
    "ReportTemplateOut",
    "SendInvoiceBody",
    "SiteAssignManagerRequest",
    "SiteAssignManagerResponse",
    "SiteCreate",
    "SiteOut",
    "SiteProvisionRequest",
    "SiteProvisionResponse",
    "SiteUpdate",
    "SubscriptionOut",
    "SubscriptionPackageCreate",
    "SubscriptionPackageOut",
    "SubscriptionPackageUpdate",
    "SubscriptionUpdate",
    "TechnicianProfileCreate",
    "TechnicianProfileOut",
    "TechnicianProfileUpdate",
    "TechnicianScheduleCreate",
    "TechnicianScheduleOut",
    "TemplateSyncResult",
    "TenantBriefOut",
    "TenantLicenseAssign",
    "TenantProvisionBody",
    "TenantProvisionOut",
    "TokenResponse",
    "UserBrief",
    "UserCreateBody",
    "UserCreateResponse",
    "UserListOut",
    "UserMeOut",
    "UserPatchBody",
    "UserPatchMe",
    "UserPublic",
    "WorkOrderCreate",
    "WorkOrderOut",
    "WorkOrderUpdate",
]
