"""JSON schema for the Standard Inspection report template (form fields)."""

STANDARD_INSPECTION_SCHEMA: dict = {
    "sections": [
        {
            "id": "sec_header",
            "title": "1. Report header & details",
            "fields": [
                {
                    "id": "inspector_full_name",
                    "type": "text",
                    "label": "Inspector full name",
                    "required": True,
                },
                {
                    "id": "inspector_title",
                    "type": "text",
                    "label": "Inspector title / role",
                    "required": False,
                },
                {
                    "id": "inspector_contact",
                    "type": "text",
                    "label": "Inspector contact (phone / email)",
                    "required": False,
                },
                {
                    "id": "inspector_license",
                    "type": "text",
                    "label": "Accreditation or license number",
                    "required": False,
                },
                {
                    "id": "property_site_name",
                    "type": "text",
                    "label": "Property / site name",
                    "required": True,
                },
                {
                    "id": "property_full_address",
                    "type": "textarea",
                    "label": "Full site address",
                    "rows": 3,
                    "required": True,
                },
                {
                    "id": "asset_unit_identification",
                    "type": "text",
                    "label": "Specific asset or unit ID",
                    "required": False,
                },
                {
                    "id": "inspection_date",
                    "type": "text",
                    "label": "Inspection date (YYYY-MM-DD)",
                    "required": True,
                },
                {
                    "id": "inspection_start_time",
                    "type": "text",
                    "label": "Start time",
                    "required": False,
                },
                {
                    "id": "inspection_end_time",
                    "type": "text",
                    "label": "End time",
                    "required": False,
                },
                {
                    "id": "environmental_factors",
                    "type": "textarea",
                    "label": "Environmental factors (weather, operational phase, site conditions)",
                    "rows": 4,
                    "required": False,
                },
            ],
        },
        {
            "id": "sec_scope",
            "title": "2. Inspection scope & methodology",
            "fields": [
                {
                    "id": "inspection_type",
                    "type": "checklist",
                    "label": "Inspection type",
                    "options": ["Pre-inspection", "Interim", "Final", "Routine / periodic"],
                    "required": True,
                },
                {
                    "id": "scope_systems_list",
                    "type": "textarea",
                    "label": "Scope — systems or machinery examined (e.g. HVAC, structural, electrical)",
                    "rows": 5,
                    "required": True,
                },
                {
                    "id": "methodology_tools",
                    "type": "textarea",
                    "label": "Methodology — tools, instruments, and test types used",
                    "rows": 4,
                    "required": False,
                },
                {
                    "id": "tests_performed",
                    "type": "textarea",
                    "label": "Specific tests performed (functional, visual, measurements)",
                    "rows": 4,
                    "required": False,
                },
                {
                    "id": "areas_not_inspected",
                    "type": "textarea",
                    "label": "Areas not inspected or deemed unsafe for entry",
                    "rows": 3,
                    "required": False,
                },
            ],
        },
        {
            "id": "sec_findings",
            "title": "3. Detailed observations & findings",
            "fields": [
                {
                    "id": "finding_interior_condition",
                    "type": "checklist",
                    "label": "Interior — overall condition",
                    "options": ["Good", "Fair", "Poor", "N/A"],
                    "required": False,
                },
                {
                    "id": "finding_interior_narrative",
                    "type": "textarea",
                    "label": "Interior — observations (objective, detailed)",
                    "rows": 4,
                    "required": False,
                },
                {
                    "id": "finding_exterior_condition",
                    "type": "checklist",
                    "label": "Exterior — overall condition",
                    "options": ["Good", "Fair", "Poor", "N/A"],
                    "required": False,
                },
                {
                    "id": "finding_exterior_narrative",
                    "type": "textarea",
                    "label": "Exterior — observations",
                    "rows": 4,
                    "required": False,
                },
                {
                    "id": "finding_electrical_conformance",
                    "type": "checklist",
                    "label": "Electrical — conformance",
                    "options": ["Conformance", "Non-conformance", "N/A"],
                    "required": False,
                },
                {
                    "id": "finding_electrical_narrative",
                    "type": "textarea",
                    "label": "Electrical — findings and defects",
                    "rows": 4,
                    "required": False,
                },
                {
                    "id": "finding_mechanical_hvac_conformance",
                    "type": "checklist",
                    "label": "Mechanical / HVAC — conformance",
                    "options": ["Conformance", "Non-conformance", "N/A"],
                    "required": False,
                },
                {
                    "id": "finding_mechanical_hvac_narrative",
                    "type": "textarea",
                    "label": "Mechanical / HVAC — findings",
                    "rows": 4,
                    "required": False,
                },
                {
                    "id": "finding_structural_condition",
                    "type": "checklist",
                    "label": "Structural — condition",
                    "options": ["Good", "Fair", "Poor", "N/A"],
                    "required": False,
                },
                {
                    "id": "finding_structural_narrative",
                    "type": "textarea",
                    "label": "Structural — observations",
                    "rows": 4,
                    "required": False,
                },
                {
                    "id": "issue_priority_summary",
                    "type": "textarea",
                    "label": "Risk / priority summary (High / Medium / Low issues)",
                    "rows": 4,
                    "required": False,
                },
            ],
        },
        {
            "id": "sec_evidence",
            "title": "4. Supporting evidence & documentation",
            "fields": [
                {
                    "id": "photo_documentation",
                    "type": "photo",
                    "label": "Photo documentation (timestamped images, annotated where possible)",
                    "max_photos": 12,
                    "required": False,
                },
                {
                    "id": "reference_documents",
                    "type": "textarea",
                    "label": "Reference documents (prior reports, manuals, SDS, OSHA or local standards cited)",
                    "rows": 5,
                    "required": False,
                },
            ],
        },
        {
            "id": "sec_results",
            "title": "5. Results, conclusions & actions",
            "fields": [
                {
                    "id": "executive_summary",
                    "type": "textarea",
                    "label": "Executive summary (critical findings for stakeholders)",
                    "rows": 5,
                    "required": False,
                },
                {
                    "id": "recommended_actions",
                    "type": "textarea",
                    "label": "Recommended actions (specific, realistic next steps)",
                    "rows": 5,
                    "required": False,
                },
                {
                    "id": "corrective_action_plan",
                    "type": "textarea",
                    "label": "Corrective action plan (responsible party, target dates, estimated man-hours)",
                    "rows": 5,
                    "required": False,
                },
                {
                    "id": "follow_up_verification_date",
                    "type": "text",
                    "label": "Planned follow-up / verification visit date",
                    "required": False,
                },
                {
                    "id": "labor_log",
                    "type": "labor_log",
                    "label_key": "labor",
                    "required": False,
                },
                {
                    "id": "parts_used",
                    "type": "parts_used",
                    "label_key": "parts",
                    "required": False,
                },
            ],
        },
    ],
}
